name: Terraform CI/CD

on:
  push:
    branches:
      - qa
permissions:
  id-token: write
  contents: read
env:
  TF_VAR_environment: qaa
  TF_VAR_sf_username: ${{ secrets.SF_USERNAME }}
  TF_VAR_sf_password: ${{ secrets.SF_PASSWORD }}
  TF_VAR_sf_account: ${{ secrets.SF_ACCOUNT }}
  TF_VAR_sf_org_name: ${{ secrets.SF_ORG }}
  TF_VAR_sf_account_identity: ${{ secrets.SF_ACCOUNT_IDENTITY }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Terraform Init
        working-directory: infra/environments/qa
        run: terraform init

      - name: Terraform Plan
        working-directory: infra/environments/qa
        run: terraform plan -input=false

      - name: Terraform Apply
        working-directory: infra/environments/qa
        run: terraform apply -auto-approve